name: boptestgym
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - idna
  - libffi
  - ncurses
  - openssl
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - readline
  - requests
  - setuptools
  - sqlite
  - tk
  - urllib3
  - wheel
  - xz
  - zlib
  - pip:
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - farama-notifications==0.0.4
      - filelock==3.12.2
      - fonttools==4.40.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - jax-jumpy==1.0.0
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.25.0
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scipy==1.11.1
      - shimmy==1.1.0
      - six==1.16.0
      - stable-baselines3==2.0.0
      - sympy==1.12
      - torch==2.0.1
      - typing-extensions==4.7.1
      - tzdata==2023.3